### ISSUE TITLE
transport: received unexpected content-type "application/json"

### ISSUE THREAD

**Issue by iyobo** [pulumiverse/pulumi-zitadel#7]
After configuring the profile and using it, I keep getting the error
 * rpc error: code = Unimplemented desc = unexpected HTTP status code received from server: 404 (Not Found); transport: received unexpected content-type "application/json"

**Comment by vavsab** [comment]
@iyobo I need at least your code example that is failing to help you.
It could be due to mixing grpc & rest apis. But need to know which resources you are trying to create and at which resource it's failing exactly.

**Comment by cenk1cenk2** [comment]
@iyobo did you ever got the chance to figure out what was wrong and why would you receive this message? In my case it happens in every kind of resource, so I bet that I am missing the correct configuration.

**Comment by cenk1cenk2** [comment]
I have immediately figured this out since the error looked simialr and will leave it here for any other fellow that will search this here.

The reason why this happens is that the provider calls the GRPC endpoints for management. And if you install the `zitadel` like as I did through helm and your ingress controller or reverse proxy that does not support mixed requests of GRPC and HTTP like I did with the `nginx`, you would explicitly have to create and mark the given paths as GRPC for the endpoints given in the API documentation [here](https://zitadel.com/docs/apis/introduction).

**Comment by driv** [comment]
For anyone else dealing with this on nginx ingress:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: GRPC
  name: my-zitadel-grpc
  namespace: default
spec:
  rules:
  - host: <your-host>
    http:
      paths:
      - backend:
          service:
            name: my-zitadel
            port:
              number: 8081
        path: /zitadel
        pathType: Prefix
```

The 2 important things being the annotation and the path
